### ISSUE TITLE
Fix the fields string

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/jsv-convert#10]
## **Describe the bug**
The fields string is generated with an extra comma at the last which is creating error while generating a CSV file. 

## **Expected behavior**
Checking for the last element and adding commas accordingly will solve the issue.

---
> This issue is reserved for @CodeAught 
---

**Comment by ankeshp03** [comment]
Hi, is this issue already assigned?
If not can I work on this issue?

**Comment by CodeAught** [comment]
@Souvikns I created PR, please review/merge code.

**Comment by Souvikns** [comment]
@ankeshp03 this issue was already created for @CodeAught I will open more issues soon, you can try those.

**Comment by ankeshp03** [comment]
Sure @Souvikns
