### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/jsv-convert#2]
> This library has been updated, though the documentation has not been updated. 

## About 
This is a little utility library for converting JSON data to CSV format. For now, the application creates a CSV format string from the JSON data, for example: 

JSON
```js
const data = [
{"language": "javascript", "rating": 5},
{"language": "java", "rating": 5}
]
```

CSV
```js
const data = `
language, rating
javascript, 5
java, 5
`
```

## TODO
- [ ] Update the readme section with a usage section giving example about what how to use the library
- [ ] Read the `src/core.ts` file and create suitable examples with explanations.

**Comment by hnishal** [comment]
Assign me this issue @Souvikns

**Comment by Souvikns** [comment]
@hnishal go-ahead, just make the pr to the development branch.
