### ISSUE TITLE
BUG: Creating unnecessary extra column in csv format

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/jsv-convert#3]
## Current Behaviour
Converting from the JSON format the CSV string currently the format is looking like 
```js
const data = `
language, rating,
javascript, 5,
java, 5, 
`
```

## Expected behavior 
The expected CSV string format should be something like this
```js
const data = `
language, rating
javascript, 5
java, 5
`
```

## Problem 
Currently, there is a comma at the end of each line which is creating an extra column. 

## Probable solution 
Removing the comma from each line should fix this issue. 
This function is responsible for generating columns in CSV format https://github.com/Ninja-Developers/jsv-convert/blob/c87e20c6b019d350eb1e3496c9479a4db10a2217/src/core.ts#L34
If we can just remove the last character after the string is generated and before concating it with the main string, we will be able to fix this issue. 

## This is the complete code responsible for generating the columns 
```ts
 generateColumns(): Array<string> {
        let columns: Array<string> = []

        this.data.forEach((el: any) => {
            let row: string = ''
            this.fields.forEach((f: string) => {
                if (el[f]) {
                    row += el[f] + ','

                } else {
                    row += ','
                }
            })
            columns.push(row)
        })

        return columns
    }

    generateCsvFormat(): string{
        let fieldString: string = ''
        this.fields.forEach((el: string) => {
            fieldString+=el+','
        })
        let colStr: string = ''
        this.columns.forEach((el: string) => {
            colStr+=el+"\n"
        })
        return `${fieldString}
${colStr}`
    }

```

**Comment by akshay399** [comment]
may i work on this please?

**Comment by Souvikns** [comment]
@akshay399 go-ahead, just make pr in the development branch.

**Comment by CodeAught** [comment]
I also want to work on it!

**Comment by Souvikns** [comment]
@akshay399 you have till today to make a pr after then this issue will be given to @CodeAught, 
I don't want to assign two people at once, as it will waste the time of one person whose work will not be merged. For the time being @CodeAught do look out for more issues that I will be making.

**Comment by Souvikns** [comment]
ok @akshay399

**Comment by Souvikns** [comment]
@CodeAught I have assigned the issue to use let me know if you need any help.

**Comment by CodeAught** [comment]
@Souvikns Getting "error: pathspec 'development' did not match any file(s) known to git" on development branch checkout.

**Comment by CodeAught** [comment]
> @Souvikns Getting "error: pathspec 'development' did not match any file(s) known to git" on development branch checkout.

Fixed it, nvm!

**Comment by CodeAught** [comment]
@Souvikns Can you please tell me how to test the code? I am getting error on running `npm test`.

 FAIL  test/test.js
  ● Test suite failed to run

    Cannot find module '../index' from 'test.js'

    > 1 | const {prepareTable} = require('../index')
        |                        ^
      2 |
      3 | test('Fake Test',()=>{
      4 |     expect(true).toBeTruthy()

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:296:11)
      at Object.<anonymous> (test/test.js:1:24)

**Comment by Souvikns** [comment]
actually, this library was first written in `javascript`, then I converted it to `typescript` and changed the API to, the **test cases** hasn't been updated yet.

**Comment by CodeAught** [comment]
> actually, this library was first written in `javascript`, then I converted it to `typescript` and changed the API to, the **test cases** hasn't been updated yet.

So How I gonna test this?

**Comment by Souvikns** [comment]
I was about to create new issues for fixing the test cases. But for now, u have to options 
- As this is written in typescript you need to first build the project this will create a dist folder then import the code from the dist folder and use jest for testing your code. Also, you have to change the `npm test` command with `tsc && jest`. 
- For just this issue you can create another file where you can import the code and test on your own by logging but do clean the code before committing.

**Comment by Souvikns** [comment]
@CodeAught I have updated the test scripts, once pull the latest changes from the upstream.

**Comment by CodeAught** [comment]
@Souvikns Created pull request, please review/merge code.

**Comment by Souvikns** [comment]
@CodeAught I have merged your code, as it has fixed the `generateColumns` function but there is this same issue in `generateFields` function. I will create a new issue for this, let me know If you want to take that, as a hacktoberfest issue.

**Comment by CodeAught** [comment]
> @CodeAught I have merged your code, as it has fixed the `generateColumns` function but there is this same issue in `generateFields` function. I will create a new issue for this, let me know If you want to take that, as a hacktoberfest issue.

Yeah, sure!

**Comment by Souvikns** [comment]
So I am closing this issue.
